//
//  PatternAnalysisView.swift
//  TrackMate
//
//  Created by Glen Mars on 4/8/25.
//
// Includes a weekly calendar for users to log mood, show bar charts of most frequent emotional tags, a timeline showing a trend in interactions, and a sentiment summary text that's generated by filtering the interaction for the current week and summarizing the most frequent person involved with emotion tag trend.

import SwiftUI
import CoreData
import NaturalLanguage

private let dateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "EEE\ndd"
    return formatter
}()

private let weekFormatter: DateFormatter = {
    let f = DateFormatter()
    f.dateFormat = "MMM d"
    return f
}()

struct PatternAnalysisView: View {
    @Environment(\.managedObjectContext)
    private var viewContext
    
    @EnvironmentObject var themeManager: ThemeManager
    
    // Fetch all interaction records ordered by timestamp
    @FetchRequest(
        entity: Interaction.entity(),
        sortDescriptors: [NSSortDescriptor(keyPath: \Interaction.timestamp, ascending: true)]
    )
    
    var interactions: FetchedResults<Interaction>
    
    @State private var selectedDay: Date?
    @State private var personSummaries: [String: String] = [:]
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 10) {
                
                Text("This Week at a Glance")
                    .font(.headline)
                    .bold()
                    .foregroundColor(themeManager.color("PrimaryText"))
                
                HStack(spacing: 12) {
                    Label("Better", systemImage: "circle.fill")
                        .foregroundColor(Color("MoodPositive"))
                    Label("Neutral", systemImage: "circle.fill")
                        .foregroundColor(.gray)
                    Label("Tough", systemImage: "circle.fill")
                        .foregroundColor(Color("MoodNegative"))
                }
                .font(.caption)
                .foregroundColor(themeManager.color("SecondaryText"))
                .padding(.bottom, 4)
                
                // Weekly Calendar with color-coded emotional states
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack {
                        ForEach(getDaysForCurrentWeek(), id: \.self) { day in
                            
                            Button {
                                selectedDay = day
                            } label: {
                                VStack {
                                    Text(day, formatter: dateFormatter)
                                        .foregroundColor(themeManager.color("SecondaryText"))
                                        .multilineTextAlignment(.center)
                                    
                                    ZStack {
                                        Circle()
                                            .fill(colorForDay(day: day).opacity(0.85))
                                            .frame(width: 50, height: 50)
                                        Circle()
                                            .stroke(
                                                selectedDay == day ? themeManager.color("AccentColor") : Color.clear,
                                                lineWidth: 3
                                            )
                                    }
                                }
                            }
                            .buttonStyle(.plain)
                            .simultaneousGesture(
                                LongPressGesture().onEnded { _ in
                                    NotificationCenter.default.post( name: .prefillInteractionDate,
                                                                     object: day
                                    )
                                }
                            )
                        }
                    }
                    .padding(.vertical, 10)
                    
                    Text("Tap a day to focus. Long‑press to prefill that date when adding a new interaction.")
                        .font(.caption)
                        .foregroundColor(themeManager.color("SecondaryText"))
                }
                                
              // Foundation Model Summary
                VStack(alignment: .leading, spacing: 12) {
                    Text("Relationship Insights")
                        .font(.headline)
                        .foregroundColor(themeManager.color("PrimaryText"))
                    
                    ForEach(getUniquePeople(), id: \.self) { person in
                        VStack(alignment: .leading, spacing: 6) {
                            Text(person)
                                .font(.subheadline.bold())
                                .foregroundColor(themeManager.color("AccentColor"))
                            
                            if let summary = personSummaries[person] {
                                Text(summary)
                                    .font(.body)
                                    .foregroundColor(themeManager.color("SecondaryText"))
                            } else {
                                HStack {
                                    ProgressView()
                                        .scaleEffect(0.8)
                                    Text("Analyzing patterns...")
                                        .font(.caption.italic())
                                        .foregroundColor(themeManager.color("SecondaryText"))
                                }
                            }
                        }
                        .padding()
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .background(themeManager.color("CardFill"))
                        .cornerRadius(12)
                    }
                }
                .task {
                    await refreshAISummaries()
                }
            }
            .padding()
        }
        .background(themeManager.color("PrimaryBackground"))
        .trackMateNav(title: "Pattern Analysis", themeManager: themeManager)
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                
            }
        }
    }
    
    // MARK: - Helper Functions
    
    // Returns the dates for the curent week (using Monday as the first day)
    func getDaysForCurrentWeek() -> [Date] {
        let calendar = Calendar.current
        let today = Date()
        var week: [Date] = []
        let weekday = calendar.component(.weekday, from: today)
        guard let startOfWeek = calendar.date(byAdding: .day, value: -(weekday - 2), to: today) else { return [] }
        for i in 0..<7 {
            if let day = calendar.date(byAdding: .day, value: i, to: startOfWeek) {
                week.append(day)
            }
        }
        return week
    }
    
    // Compute a color for a given day based on the emotional tags of that day's interactions
    func colorForDay(day: Date) -> Color {
        let dailyInteractions = interactions.filter {
            Calendar.current.isDate($0.timestamp ?? Date(), inSameDayAs: day)
        }
        let negativeEmotions = ["Sad", "Anxious", "Confused", "Belittled", "Angry", "Guilty", "Invalidated", "Unsafe"]
        let positiveEmotions = ["Happy", "Calm", "Loved", "Empowered", "Safe"]
        var score = 0
        for interaction in dailyInteractions {
            if let tags = interaction.emotionTags as? [String] {
                for tag in tags {
                    if negativeEmotions.contains(tag) {
                        score -= 1
                    } else if positiveEmotions.contains(tag) {
                        score += 1
                    }
                }
            }
        }
        if score < 0 {
            return Color("MoodNegative")
        } else if score > 0 {
            return Color("MoodPositive")
        } else {
            return .gray
        }
    }
        
    // Computes a sentiment summary string for the current week
    func sentimentSummary() -> String {
        let calendar = Calendar.current
        guard let startOfWeek = calendar.date(from: calendar.dateComponents([.yearForWeekOfYear, .weekOfYear], from: Date()))
        else {
            return "Error computing start of week."
        }
        
        let weekInteractions = interactions.filter { interaction in
            if let timestamp = interaction.timestamp {
                return timestamp >= startOfWeek
            }
            return false
        }
        
        // Total interactions for the week
        let total = weekInteractions.count
        
        // Determine which person appears most frequently this week
        let individualCount = Dictionary(grouping: weekInteractions, by: { $0.personName ?? "Unknown" })
        let topIndividual = individualCount.max { a, b in
            a.value.count < b.value.count
        }?.key ?? "Unknown"
        let topIndividualCount = individualCount[topIndividual]?.count ?? 0
        
        return "You logged \(total) interactions this week. \(topIndividualCount) involved \(topIndividual)."
            
    }
    
    private func refreshAISummaries() async {
        // Group interactions by name
        let grouped = Dictionary(grouping: interactions) { $0.personName ?? "Unknown" }
        
        for (person, logs) in grouped {
            // Gets notes to be analyzed
            var combinedText: [String] = logs.compactMap { $0.notes }.filter { !$0.isEmpty }
            _ = logs.compactMap { $0.notes }.filter { !$0.isEmpty }
            
            // Gets content from linked journal entries
            for interaction in logs {
                if let linkedEntries = interaction.journalEntries as? Set<JournalEntry> {
                    let journalTexts = linkedEntries.compactMap { $0.content }.filter { !$0.isEmpty }
                    combinedText.append(contentsOf: journalTexts)
                }
            }
            
            // Check that prompt isn't empty
            guard !combinedText.isEmpty else {
                await MainActor.run {
                    personSummaries[person] = "No notes recorded yet to analyze."
                }
                continue
            }
            
            // Call to FoundationModels file
            if let summary = try? await AIInsightService.generateSummary(for: person, notes: combinedText) {
                await MainActor.run {
                    personSummaries[person] = summary
                }
            }
        }
    }
    
    private func getUniquePeople() -> [String] {
        Array(Set(interactions.compactMap { $0.personName })).sorted()
    }
}

extension Notification.Name {
    static let prefillInteractionDate = Notification.Name("prefillInInteractionDate")
}
